DISPLAY_LINE = "****************************************************************"

NO_DATA_VALUE = "-"

SUCCESS_TEXT_1 = "\033[1;37;32m"
SUCCESS_TEXT_2 = "\033[0;0m"

WARNING_TEXT_1 = "\033[1;37;31m"
WARNING_TEXT_2 = "\033[0;0m"

FIRST_MULTI_THREAD_NAME = "Thread-1 (starting_threading_process)"
SECOND_MULTI_THREAD_NAME = "Thread-2 (starting_threading_process)"

COLUMN_TITLE = "title"
COLUMN_PATH = "s3_path"

SEARCHED_INVALID_FORMAT_FILE = ".pdf"
SEARCHED_INVALID_FILE_NAME = "tersedia"

SEARCHED_KEYWORDS = ["Sanksi", "Berlaku"]

FILE_NOT_FOUND = "FILE NOT FOUND"

EMPTY_SEARCHED_DATA_VALUE = "SEARCHED REGULATION NOT FOUND"

EMPTY_RESOURCE_DATA_WARNS = "EMPTY RESOURCE DATA"

FILE_SUCCESSFULLY_SAVED = "FILE WAS SUCCESSFULLY SAVED! :>"

FILE_NOT_FOUND_TABLE_COL_NAME = ["NO.", "LIST OF FILES", "STATUS"]
KEYWORD_TABLE_COL_NAME = ["NO.", "KEYWORDS", "LIST OF SEARCHED REGULATIONS"]

NUM_OF_THREADS = 3

SINGLE_THREAD_SUCCESSFULLY_PROCEED = SUCCESS_TEXT_1 + "SINGLE-THREAD SUCCESSFULLY PROCEED!" + SUCCESS_TEXT_2
MULTI_THREAD_SUCCESSFULLY_PROCEED = SUCCESS_TEXT_1 + "MULTI-THREAD SUCCESSFULLY PROCEED!" + SUCCESS_TEXT_2

SINGLE_THREAD_PROCESS_DONE = "SINGLE-THREAD PROCESS DONE"
MULTI_THREAD_PROCESS_DONE = "MULTI_THREAD PROCESS DONE"

EXCEl_FILE_ENGINE = "openpyxl"

# noinspection SpellCheckingInspection
EXCEL_FILE_RESOURCE_DATA = "BATAM.xlsx"
EXCEL_FILE_RESOURCE_DATA_PATH = "resource_files/"

TEMP_RESOURCE_FILE_DIRECTORY = "task_files"
TEMP_IMAGE_DATA_DIRECTORY = "task_file_images"

IMPORT_RESOURCE_FILE_DATA_PATH = "/task_files/"
EXPORT_WORKING_FILE_DATA_PATH = "task_files/"
EXPORT_IMAGE_DATA_PATH = "task_file_images/"

DEF_IMAGE_DATA_FORMAT = "jpeg"

IDN_LANG_CODE_ISO_619 = "id"

REQ_HTTP_ERROR_ENCOUNTERED = WARNING_TEXT_1 + "REQUEST HTTP ERROR ENCOUNTERED" + WARNING_TEXT_2
REQ_CONNECTION_TIMEOUT_ENCOUNTERED = WARNING_TEXT_1 + "REQUEST CONNECTION TIMEOUT ENCOUNTERED" + WARNING_TEXT_2
